### ISSUE TITLE
test password feature

### ISSUE THREAD

**Issue by johnfelipe** [OpeningDesign/draw#5]
How can test password feature?

![pantallazo-0351](https://user-images.githubusercontent.com/428820/31025954-294096e4-a50a-11e7-8c17-145e7c526b2b.png)

An when draw not show password window

**Comment by bytesnz** [comment]
With those settings (the editPassword Object will override the string as it is second), only the drawing /d/protected will be protected with a password - you will be able to view the drawing, but you won't be able to edit it without entering the password (you will be prompted when you changed to a tool that will edit the drawing)

**Comment by johnfelipe** [comment]
/*
	  This file must be valid JSON. But comments are allowed

	  Please edit settings.json, not settings.json.template
	*/

	{
	  //IP and port which etherpad should bind at
	  "ip" : "0.0.0.0",
	  "port" : 9002,

	  // Uncomment to remove rooms after a certain amount of time of inactivity.
	  // Value can either be just a number (for the number of seconds), or a
	  // a number and a unit (min, hr, or day).
	  // "removeUnused": "1day",

	  // Uncomment the following line to require the given password to be entered
	  // before all drawings can be edited
	  "editPassword": "jaime123",
	  // The edit password can also be an object containing room names and
	  // passwords as key/value pairs
	  "editPassword": {
	   "protected": "jaime"
	  },
	  // Uncomment to add a timeout on authentication tokens. Value can either be
	  // just a number (for the number of seconds), or a number and a unit
	  // (min, hr, or day)
	  // "authenticationTimeout": "1day",

	  //The Type of the database. You can choose between dirty, postgres, sqlite and mysql
	  //You shouldn't use "dirty" for for anything else than testing or development
	  "dbType" : "dirty",
	  //the database specific settings
	  "dbSettings" : {
		 "filename" : "var/dirty.db"
	  },

	  /* An Example of MySQL Configuration
	  "dbType" : "mysql",
	  "dbSettings" : {
		"user"    : "root", 
		"host"    : "localhost", 
		"password": "", 
		"database": "etherdraw"
	  },
	  */

	  /* The default selected tool - 'pencil', 'brush', 'select' */
	  "tool": "brush"
					 
	  /* Example SSL Configuration
		"ssl" : {
		  "key": "/path/to/key.key",
		  "cert": "/path/to/cert.crt"
		}
	  */

	}

Is not working, i have **jaime** room and **jaime123** password and is not working

**Comment by bytesnz** [comment]
So if you want to protect a room named jamie your editPassword should be:
```
"editPassword": {
  "jamie": " jamie123"
}
```
