### ISSUE TITLE
how test 11 icons i have only 8

### ISSUE THREAD

**Issue by johnfelipe** [OpeningDesign/draw#6]
![pantallazo-0352](https://user-images.githubusercontent.com/428820/31025992-525fd86e-a50a-11e7-9d4e-b1c2e232c9f5.png)

8 icons

![pantallazo-0353](https://user-images.githubusercontent.com/428820/31026015-609e1e2c-a50a-11e7-8338-b76a05bcc219.png)

11 icons

**Comment by bytesnz** [comment]
Looks there are a few commits missing from this repo. You can try them on draw.meldce.com (#bytesnz/draw)

**Comment by theoryshaw** [comment]
i just hid them...

https://github.com/OpeningDesign/draw/commit/1479b3c49a9b911c23eb5bc2dfb7712fc42023f2

**Comment by tfodden** [comment]
Hi Ryan,

 

Do you want to remove me from GitHub?

 

Hope things are going well!

 

Thanks,

Tony Fodden

**Comment by bytesnz** [comment]
Ah yes, that's right.
