### ISSUE TITLE
how solve "DirtyDB is used. This is fine for testing but not recommended for production."

### ISSUE THREAD

**Issue by johnfelipe** [OpeningDesign/draw#8]
felipe@cloud:~/draw$ bin/run.sh
	Ensure that all dependencies are up to date...
	start...
	DirtyDB is used. This is fine for testing but not recommended for production.
	Access Etherdraw at http://0.0.0.0:9002

What i need to change for solve that warning?

**Comment by bytesnz** [comment]
Use a database that isn't dirtyDB

**Comment by johnfelipe** [comment]
Where can do that change?, path pls...
Stay alert

2017-10-17 10:07 GMT-05:00 Jack Farley <notifications@github.com>:
